@startuml
'skinparam dpi 300
'scale 1024 width

class Logger
{
  + info(message)
  + debug(message)
  + error(message)
  + info_all(message)
  + debug_all(message)
  + error_all(message)
  - _log(message, level)
  - _log_all(message, level)
}

abstract class ObsBuilder
{
  - input_path : str
  - mapping_path : str
  - log : Logger

  + create_obs_group(input_path, mapping_path, category, env)
  + create_obs_file(input_path, mapping_path, output_path)
  - make_description()
  - make_obs(comm)
}

class MarineObsBuilder
{
  # convert_temp_to_celsius(name)
  # convert_depth_from_pressure(name)
  # add_preqc_var(name)
  # add_error_var(name, error)
  # add_seq_num(self)
  # add_ocean_basin(self)
}

class SatWndObsBuilder
{
  # compute_wind_components(wdir, wspd)
}

class SatWndAhiObsBuilder
{
  - make_description()
  - make_obs(comm)
}

Logger <--* ObsBuilder
ObsBuilder <|-- MarineObsBuilder
ObsBuilder <|-- SatWndObsBuilder
SatWndObsBuilder <|-- SatWndAhiObsBuilder


@enduml
